### ISSUE TITLE
Scam ublock homepage link (heads up)

### ISSUE THREAD

**Issue by quangIO** [nyu-ossd-s20/activity1_browser_extension#1]
[Previous discussion on Reddit](https://www.reddit.com/r/uBlockOrigin/comments/b8vr9j/got_fooled_into_installing_ublockorg_chrome/) 

A wrong (scammy) link to ublock homepage was posted. @ryanhanli could you take it down?

**Comment by ryanhanli** [comment]
Fixed it.  Thanks.
